# swagger : http://localhost:8080/swagger-ui/index.html

###
# 게시판 목록 조회
GET http://localhost:8080/boards

###
# 게시글 상세 조회
GET http://localhost:8080/boards/8

###
# 게시글 등록
POST http://localhost:8080/boards
Content-Type: application/json

{
  "title": "9주차 목표 과제",
  "content": "WebFlux, Spring Cache",
  "writer": 7
}

###
# 게시글 수정
PUT http://localhost:8080/boards/8
Content-Type: application/json

{
  "title": "5주차 목표 과제",
  "content": "table join, xml",
  "writeName": 18,
  "modifyName": 18
}

###
# 게시글 삭제
DELETE http://localhost:8080/boards/8