# swagger : http://localhost:8080/swagger-ui/index.html

###
# 회원 목록 조회 0
GET http://localhost:8080/users

###
# 회원 상세 조회
GET http://localhost:8080/users/11

###
# 회원 등록
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "ghghgh태린",
  "email": "taerin@email.com",
  "gender": 2
}

###
# 회원 수정
PUT http://localhost:8080/users/4
Content-Type: application/json

{
  "userId": 4,
  "name": "홍길asdfasdf동",
  "email": "gildong@email.com",
  "gender": 1
}

###
# 회원 삭제
DELETE http://localhost:8080/users/11