server:
  port: 8080

# 기본 환경(로컬)에서 적용되는 DB 설정
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_jdbc
    username: taerin
    password: '0000'

#  flyway:
#    enabled: true # flyway를 사용하겠다
#    baseline-on-migrate: true # flyway는 버전 정보를 flyway_shcema_history 라는 테이블에서 관리하는데 해당 테이블을 자동으로 생성해주는 옵션입
#    url: jdbc:mysql://localhost:3306/data_jdbc
#    user: taerin
#    password: '0000'

  logging:
    level:
      org:
        springframework:
          jdbc:
            core: TRACE
